### ISSUE TITLE
Value error on reshaping image

### ISSUE THREAD

**Issue by rachmadaniHaryono** [mzucker/noteshrink#5] opened 2016-09-24 08:15 UTC
Python 2.7.12 (default, Jul  1 2016, 15:12:24)

```
Traceback (most recent call last):
  File "./noteshrink.py", line 585, in <module>
    main()
  File "./noteshrink.py", line 582, in main
    notescan_main(options=get_argument_parser().parse_args())
  File "./noteshrink.py", line 557, in notescan_main
    samples = sample_pixels(img, options)
  File "./noteshrink.py", line 340, in sample_pixels
    pixels = img.reshape((-1, 3))
ValueError: total size of new array must be unchanged
```
![test1](https://cloud.githubusercontent.com/assets/6340878/18807121/fc3c95e6-8271-11e6-97df-8a4c4702df7c.jpg)

i have installed all requirements except `notescan`m which isn't pip installable.

**Comment by mzucker** [comment] 2016-09-24 13:34
I tried running the script on the photo you attached, and it worked fine.

"notescan" is simply the original name of the repo/project before it was noteshrink, it has now been changed in the requirements.txt.

Not sure why this error is occurring. What output do you see if you insert the line

    print '*** image has shape', img.shape, '***'

immediately before line 340?

**Comment by rachmadaniHaryono** [comment] 2016-09-24 13:52
1

**Comment by mzucker** [comment] 2016-09-24 15:17
That's not expected behavior, but I don't quite know why that might be the case. I'm guessing that it's a difference between one of the package versions in your environment and mine, but can't for the life of me think of what it might be.

Closing this for now because you found a work-around.

**Closed by mzucker** 2016-09-24 15:17 UTC
